[package]
name = "blurlock"
version = "0.1.0"
authors = ["Robin McCorkell <robin@mccorkell.me.uk>"]
edition = "2018"

[dependencies]
winit = "0.23.0"
async-std = { version = "1.7.0", features = ["attributes"] }
env_logger = "0.8.1"
log = "0.4.11"
wgpu = "0.6.0"
futures = "0.3.8"
sctk = {package = "smithay-client-toolkit", version = "0.12.0"}
cgmath = "0.17.0"
bytemuck = "1.4.1"
shaderc = "0.7.0"
glob = "0.3.0"
rand = "0.7.3"
anyhow = "1.0.34"
image = "0.23.12"

[build-dependencies]
shaderc = "0.7.0"
glob = "0.3.0"
